### ISSUE TITLE
RefreshToken ConsumedTime rework/bug fixes

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#1102]
* Add new consumed delete delay, default to TimeSpan.Zero
* Remove RemoveConsumedTokens option
* Use new TimeSpan to determine if we delete old RT immediately
* Use new  TimeSpan  in token cleanup service's RemoveConsumedPersistedGrantsAsync
* Document this change, and the features for the grace period (override AcceptConsumedTokenAsync) and how to detect re-use/compromise for revocation
* Consider change default RT usage to re-use (perhaps in 7.0, not 6.3)

**Comment by brockallen** [comment]
related? https://github.com/DuendeSoftware/IdentityServer/issues/1065

**Comment by brockallen** [comment]
> Consider change default RT usage to re-use (perhaps in 7.0, not 6.3)

We should do some real thinking and consider how/if this affects things in 7.0. IOW, is this change worth it?

**Comment by josephdecock** [comment]
> related? #1065

Yes, IIRC this issue is basically our notes from when we worked on that PR

**Comment by josephdecock** [comment]
> Add new consumed delete delay, default to TimeSpan.Zero

This we did.

> Remove RemoveConsumedTokens option

This option actually stays, on the theory that some users want to retain consumed tokens indefinitely for auditing purposes.


> Use new TimeSpan to determine if we delete old RT immediately

We ended up with a separate new setting for that. A separate flag simplifies the implementation because the token cleanup job and the refresh token service don't have a good way to share options. 

>  Use new TimeSpan in token cleanup service's RemoveConsumedPersistedGrantsAsync

This we did.

>  Document this change, and the features for the grace period (override AcceptConsumedTokenAsync) and how to detect re-use/compromise for revocation

Documentation for this change is tracked [here](https://github.com/DuendeSoftware/docs.duendesoftware.com/issues/229)
Grace period is mentioned [here](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#one-time-refresh-tokens) but could be expanded, and doesn't address how to detect compromise. Those notes are added grace period are added to linked issue.
 

> Consider change default RT usage to re-use (perhaps in 7.0, not 6.3)

 Agree, this is a good change to make in 7.0. Added to https://github.com/DuendeSoftware/IdentityServer/issues/1128, which is now tracking all the config changes we'd like to make.
