### ISSUE TITLE
Consider allowing customization of PromptValuesSupported 

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer#1530]
Keep the existing behavior that using an unsupported prompt value is an error, but add the ability to extend the collection of supported values to facilitate customization (for e.g., to support an experimental/new spec). See https://github.com/DuendeSoftware/Support/issues/1142

**Comment by JuliusPC** [comment]
Hi,

we are currently planning the update of IdentityServer 6.3.x to the most recent version of IdentityServer. Will this feature be implemented before support for IdentityServer 6.3.x ends in November 2024? If not, we need to implement a workaround on our side since our application makes use of custom prompt values.

**Comment by josephdecock** [comment]
@JuliusPC - based on this conversation and the linked issue, I've moved this into the 7.1 milestone. Milestones should be understood as our goals that may change rather than a hard commitment, but this looks like a pretty straightforward change to make and having it in the milestone helps keep track of it as a goal for 7.1. There's no official release date for 7.1 yet, but historically we have made our releases about a month after new .NET versions go live when we are releasing an update that adds support for a new .NET version.

**Comment by JuliusPC** [comment]
Thank you for the update, @josephdecock! Even if this feature makes it into 7.1, we'll have to come up with something because support for 6 will unfortunately end the month before.

If the support end-of-life was only after the release of 7.1, we could still migrate to the mechanism in 7.1 or implement a workaround for the prompts...

(We are currently using 6.3.10 with .NET 8.)

**Comment by josephdecock** [comment]
Ok, I see the difficulty you're in with not being able to upgrade to 7.0 because of our stricter validation there. This is such a small and non-breaking change that I think the best thing is for us to just put it into the next 7.0.x release.

**Comment by josephdecock** [comment]
@JuliusPC we released IdentityServer 7.0.7 today, with customizable prompt modes! I'm closing this issue but please let me know if you have any more questions.
