### ISSUE TITLE
Claim Issuer not persisted when using Server Side Sessions

### ISSUE THREAD

**Issue by dheardal** [DuendeSoftware/IdentityServer#1546]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**

8

**Describe the bug**

When using Server Side Sessions, the issuer of the claim is not persisted, which means on rehydration the issuer is set to `LOCAL_AUTHORITY` which is the default for a claim.

This causes issues with the Sustainsys.SAML2 Single Logout as it uses the issuer from the claim in order to redirect to the identity provider. See https://github.com/Sustainsys/Saml2/blob/3780695449868fdeb708f0665eadd042a1a27153/Sustainsys.Saml2/WebSSO/LogOutCommand.cs#L168

**To Reproduce**

Setup identity server that uses Sustainsys.SAML2 as an external identity provider with single logout enabled and enable server side sessions.
Then attempt to logout.

**Expected behavior**

The claim should be rehydrated with the original issuer in order to allow single logout.

--

The question is, was the omission of persisting the issuer a design choice and this should be handled in a different manner?

**Comment by kevinmcody** [comment]
Other than turning off server side sessions, is there a workaround for this that would still allow SAML2 Single Logout?

**Comment by JscNZ** [comment]
I just found this change as it was causing some unexpected behaviour in our application after updating to 7.1.0 where we were ending up with duplicate claims in tokens.

Turns out the `DefaultTokenService` was now not removing inadvertently added duplicate claims which when added to the principal had different issuers. After the upgrade the [ClaimComparer](https://github.com/DuendeSoftware/IdentityServer/blob/5c92e25497355a5ef9c6b2e4f61eece847ebbc7b/src/IdentityServer/Services/Default/DefaultTokenService.cs#L197) in the default token service saw them as distinct where before the duplicate claim was stripped because the issuers were different instead of both being `LOCAL_AUTHORITY`.

Hopefully anyone comes across similar going forwards this might help explain unexplained behaviour!
