### ISSUE TITLE
Client Secret usage audit

### ISSUE THREAD

**Issue by jasonliao-cb** [DuendeSoftware/IdentityServer#1614]
**Which version of Duende IdentityServer are you using?**
6.1.8

**Which version of .NET are you using?**
6

**Describe the bug**

we have set the client secrets management so each client can have the secret rotated, but it is difficult to tell the last time a secret was used or the client's last activity. we see the AWS secret can have the last used information, is it possible we can save this info on the secret level so we can track the usage?

**Expected behavior**

maybe a new field in the client secret table for the last used

**Comment by jasonliao-cb** [comment]
Thanks, @AndersAbel, for moving this here.

Is there any expectation on which version/schedule we can expect to see this feature implemented? Our company uses Identity Server as our base framework and we've extended some features. The security audit feature is a higher priority for us, and we are keen to know its timeline.

**Comment by josephdecock** [comment]
@jasonliao-cb, thanks for sharing your thoughts and ideas about this. 

My suggestion to you is to create audit tables that are separate from the client secret tables, rather than trying to extend our entities. Extending the entities isn't something that the EF store implementation was really designed for, but it is possible to create your own entities that have relationships to our entities, which could include your audit data.

We're considering various ideas of how to make a store that is more conducive to custom extension as part of a larger architectural change, but it isn't an immediate item on our release calendar. I'm going to close this issue, but feel free to reopen if you'd like to discuss more. We do appreciate the feedback!
