### ISSUE TITLE
How do I refuse your package when including aspnetcore core packages?

### ISSUE THREAD

**Issue by TechnikEmpire** [DuendeSoftware/IdentityServer#459]
How do I make sure I don't use your code in .net 6 asp projects? They seem injected into the framework now and I don't want to be bound by your license.

**Comment by TechnikEmpire** [comment]
So if I use other template then 100% of your code will be excluded? Because functions pulling in your interfaces appear to be integrated directly into core libraries. Give the non-foss nature of your software that will mean my company won't touch the whole stack with a 10 foot pole so I need to be sure to purge it.

**Comment by TechnikEmpire** [comment]
Sorry for the rantish tone I'm just upset that I've been trying to get the multinational I work for to adopt asp net core, they've been pushing back and now this legal contamination will 100% kill it. When there's giant warnings on the built in templates that open saying you need a license at the cost of a kidney per year I mean its DOA so any help would be appreciated.

**Comment by hhariri** [comment]
@TechnikEmpire You work for a multinational company and yet are upset because a small company that provides an invaluable service wants to charge money for software they make. Additionally you're offensive about it. This sense of entitlement is exactly why  Free Open Source Software is not sustainable. It's people abusing other people's work.
