### ISSUE TITLE
Prompt=login inside request object results in loop

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#46]
https://github.com/IdentityServer/IdentityServer4/issues/4971

**Comment by brockallen** [comment]
My initial thought is that we add an extra param when redirecting to login to capture the original prompt, and then when we load that info via the IIdentityServerInteractionService, we know to apply the original values to the AuthorizeRequestContext object model. Also, then, on the authorize endpoint callback, we can use the same technique (since presumably that EP is post-login/consent) so we can detect that workflow scenario.

As for JAR requests, it's trickier. I'd want to threat model a bit more to consider if the JAR can be circumvented in some way. If the request object is passed via cookie message to the login page, then we could be more confident of no tampering then perhaps that becomes an additional requirement when using JAR.

So for v5, I think we can easily get this done for params via query string.
