### ISSUE TITLE
Customized SPA login page (content/url)

### ISSUE THREAD

**Issue by jafarabadi** [DuendeSoftware/IdentityServer#526]
I'm looking for a way to have a customized SPA (react/angular) login page beside of my Duende Identity Server API (developed in ASP.NET 6.0)

I googled it all day and just i found this [article](https://medium.com/@piotrkarpaa/using-spa-react-angular-ui-with-identity-server-4-dc1f57e90b2c) 

Which is not working because of removed requestedscopes from authorizationrequest.

**Comment by brockallen** [comment]
You're asking if the login page in your IdentityServer can be written as a SPA? The answer is yes. 

We have a sample here: https://docs.duendesoftware.com/identityserver/v5/samples/ui/#spa-style-login-page

**Comment by jafarabadi** [comment]
> You're asking if the login page in your IdentityServer can be written as a SPA? The answer is yes.
> 
> We have a sample here: https://docs.duendesoftware.com/identityserver/v5/samples/ui/#spa-style-login-page

Infact NO :sweat_smile: I developed an integrated user interface (React&Redux) which has login page and user management modules, it's url has different port number from my identity server but your awesome library just approved local routes for login url.

**Comment by brockallen** [comment]
Well, you can build any login page you want, but SSO relies upon redirects to the IdentityServer host so that the SSO cookie can be presented. That's just how SSO works with the OIDC spec.

**Comment by jafarabadi** [comment]
> Well, you can build any login page you want, but SSO relies upon redirects to the IdentityServer host so that the SSO cookie can be presented. That's just how SSO works with the OIDC spec.

Thanks :bowing_man: In case of my requirements this [SPA Sample](https://docs.duendesoftware.com/identityserver/v5/samples/ui/#spa-style-login-page) is enough.

**Comment by GFoley83** [comment]
@brockallen Is it possible to use a completely standalone SPA for login? i.e. one hosted on S3 for ex. /  not embedded in a .NET project?

It looks like you still have to map login and logout so not sure how that would work

https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/UserInteraction/SpaLoginUi/IdentityServerWithSpaLogin/Startup.cs#L31C1-L34C67
```cs
            services.AddIdentityServer(options =>
            {
                options.UserInteraction.LoginUrl = "/login.html";
                options.UserInteraction.ConsentUrl = "/consent.html";
                options.UserInteraction.LogoutUrl = "/logout.html";
                options.UserInteraction.ErrorUrl = "/error.html"; 
            });
```

**Comment by josephdecock** [comment]
The user interaction urls are configuring where IdentityServer will redirect when it determines that it needs to display interactive UI. Those don't have to be relative urls, so I don't think that's your main concern. 

What you will run into though, is that your separate ui needs to be able to interact with the cookies of IdentityServer, and needs to be able to interact with the ASP.NET Authentication pipeline. The contract between IdentityServer and the UI is that IdentityServer redirects to the UI, the UI authenticates, calls SignInAsync (issues the ASP.NET auth cookie), and then redirects back to the IdentityServer middleware. 

You could theoretically add API endpoints that your standalone spa would call which could do the server side work that is needed and issue the appropriate cookies. But you'd have to make sure that 3rd party cookie blocking and the samesite cookie attribute don't cause issues. Maybe if through some hosting trickery you could arrange so that requests to identity.example.com/your/custom/ui were routed to your s3 bucket, and all other requests to identity.example.com went to your identity server host you could work around that.

**Comment by josephdecock** [comment]
It's fine to include user management apis in your identity server. There's builtin support for adding apis in general - see [here](https://docs.duendesoftware.com/identityserver/v6/apis/add_apis/). A separate app could certainly obtain access tokens from IdentityServer and pass them back to those apis in IdentityServer. This user management site could be hosted anywhere, as long as you configure it as an IdentityServer client.

On the other hand, building the login UI in javascript can be done, but I would avoid hosting it on a separate domain - even a sibling subdomain of your identity server - to avoid issues with CORS, cookie domains, etc.

**Comment by GFoley83** [comment]
Thank Joseph. I actually wasn't aware of the built in support for adding APIs, that's awesome. Other than that, the strategy you're talking about it effectively what we're doing at the moment, which seems to work well so far, so that's great. 

I think you might be right about keeping the UI and the identity APIs more or less together, like your [sample login spa](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/UserInteraction/SpaLoginUi). One of the reasons I was looking to keep sign in/up SPA & identity APIs separate was an external constraint in that I've a front-end (React) dev and a back-end (.NET) dev lined up to work on this and each knows very little about the others stack. And so embedding a React SPA into the Identity project via the `wwwroot` folder wasn't my first choice. However it now seems to be the path of least resistance.
