### ISSUE TITLE
Sign your assemblies

### ISSUE THREAD

**Issue by jlchavez** [DuendeSoftware/IdentityServer#587]
**Which version of Duende IdentityServer are you using?**

5.2.0.0

**Which version of .NET are you using?**

6.0.0.0

**Describe the bug**

CSC : warning CS8002: Referenced assembly 'Duende.IdentityServer, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**To Reproduce**

1 - Create any project
2 - Add a snk file
3 - Setup signing
4 - Add a reference to your assemblies
5 - Compile!

**Expected behavior**

NO CS80002 Error

**Comment by leastprivilege** [comment]
Why is this a bug? Why are you using strong naming at all - especially on .NET Core?

**Comment by brockallen** [comment]
@jlchavez Do you have any comments you want to add to this issue?

**Comment by avivanoff** [comment]
> Why is this a bug? Why are you using strong naming at all - especially on .NET Core?

For the same reason Microsoft still strong names their framework assemblies even in .NET 8.

**Comment by leastprivilege** [comment]
What is the reason?

**Comment by RPaulProxy** [comment]
I don't have any authority here, but I'll say as a developer who is very recently moving from classic .NET Framework to .NET Core (and adopting the latest Identity Server, upgrading from v3 (!)), it took me a while to disentangle myself from the former "best practices" of strong-name signing everything, to the new best practices of not signing high-level or application-level code.  It's a choice to strong-name sign the lowest level, most fundamental things (like Microsoft does), if for no other reason that that is required in order to allow any strong-name signing.  But it ultimately gets in the way, doesn't really provide meaningful security, and isn't recommended any more.  So I read Dominick's question as, what is _your_ reason - you're not Microsoft, not building the fundamental infrastructure of the system - are you?

**Comment by leastprivilege** [comment]
IIRC Microsoft has some legacy reasons for strong naming to make their build system work. 

It sounded like the previous poster had knowledge of some practical benefits of strong naming. I am interested to hear them.
