### ISSUE TITLE
Consider sliding expiration for reference tokens

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#603]
e.g. PAT scenario - "be valid forever, but auto expire after 30 days of not being used"

**Comment by brockallen** [comment]
If we did this, then there's no need for a refresh token.

**Comment by SomeDude2341** [comment]
Hello, I don't mean to intrude. There's no longer a we in the I of this subject matter anymore as some people did not previously agree with it. Regardless, I have been reviewing your issues and started reviewing some source of this trusted solution, this seemed like a good spot to start.

Is my current conclusion/assumption wrong that identity server reference tokens are created instead of JWTs when specified as to be used as in cache response?

**Comment by brockallen** [comment]
We've decided that we will not implement this.
