### ISSUE TITLE
Minor logic issues in EntityFramework DeviceFlowStore

### ISSUE THREAD

**Issue by tillig** [DuendeSoftware/IdentityServer#735]
**Which version of Duende IdentityServer are you using?**

6.0.4

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

Something I noticed while trying to use the EntityFramework storage objects as an example so I can create a backing data store in Cosmos DB, both of which are in [DeviceFlowStore](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/Stores/DeviceFlowStore.cs):

1. When [the `ToEntity` method](https://github.com/DuendeSoftware/IdentityServer/blob/a363d92ababf6348a9b0a584a8448b70be292fc7/src/EntityFramework.Storage/Stores/DeviceFlowStore.cs#L195) converts a `DeviceCode` to a `DeviceFlowCodes` entity, it does _not_ set [the `DeviceFlowCodes.SessionId` property](https://github.com/DuendeSoftware/IdentityServer/blob/ffa4da997b44dcb32103bb26a919fb14cd1cf0f5/src/EntityFramework.Storage/Entities/DeviceFlowCodes.cs#L44). I'm not sure if this is intentional or an oversight.
2. In `UpdateByUserCodeAsync` [the incoming `DeviceCode` gets converted to an entity](https://github.com/DuendeSoftware/IdentityServer/blob/a363d92ababf6348a9b0a584a8448b70be292fc7/src/EntityFramework.Storage/Stores/DeviceFlowStore.cs#L138) but the converted entity isn't really used; instead, it seems like an end-around to avoid calling the `IPersistentGrantSerializer.Serialize` method directly. Again, unclear if this is intentional or an oversight.

I don't actually use Entity Framework so while I recognize there's some magic going on with entities getting changed and marked dirty and database contexts determining what changes to save and so on, I'm not sure if that's the reason this stuff is happening.

If it turns out these are oversights, I'd be happy to submit a PR to fix it.

**Comment by brockallen** [comment]
Hi, thanks for opening this issue. Just now had time to investigate.

1: Yep, you're right. Also, `Description` is not being set either. But re-examining the code, `ToModel` is only ever used on creation and those values won't be present since that's during a backchannel call from the device client.

2: Yes, also a good observation. This is where the `SessionId` and `Description` should be set, and I agree the call to `ToModel` is unnecessary. So a better approach would be to call the serializer directly. The only concern here is that `ToModel` is virtual, so this would be a breaking change. I know we have people using device flow, but I don't know if they override this API.

**Comment by brockallen** [comment]
I think I will do a small fix now to update the SessionId and Description. And then for v7.0 re-think the ToModel API.

**Comment by brockallen** [comment]
Looks like ToModel was used elsewhere to, so I just removed the unused call to it and did the serialization call directly.
