### ISSUE TITLE
Add nullable reference annotations

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/IdentityServer#749]

**Comment by stefannikolei** [comment]
I could help you with this task. I just did that in another project. This will need high effort and good testing.

The hardest part is getting the DB Models right. For those a decision must be made. Should they generate the same database or should they rewritten how they where intended.

For example when you think you have the property string ClientId {get; set;} 
To not generate any migrations you need to make string? ClientId {get; set;} out of it. But when you want to be correct about your models you should go with string ClientId because it makes no sense to create an client without an clientId.

This could also be done in multiple steps.

@leastprivilege what do you think?

**Comment by leastprivilege** [comment]
Thanks!

This is part of our "developer centric features" push in 6.2.

We def want to go through the exercise ourselves - but good to know you have experience with that for review / help!

**Comment by brockallen** [comment]
To get started, maybe we should just add these to the public extensibility points (interfaces, models, etc).
