### ISSUE TITLE
Improve logging on DP failures

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/IdentityServer#973]
Perhaps emit better log saying what item/record can't be unprotected, and say old DP keys can't be accessed to unprotect, and indicate the ID of the record to remove if they no longer need it.

**Comment by mantasaudickas** [comment]
I have a small request to improve logging even further.

Identity server on its own does quite a lot of logging at error level. But some of these errors actually are NOT errors.
For example, client made a request to get a token, but then cancelled request for whatever reason. Since dotnet triggers request cancellation token - it is raised as Task Cancelled (or more general Operation Cancelled exception and logged as error by identity server. While technically it is an error - but from operational point of view - it can be treated as warning.

Similar situation also with such errors:
- The client has disconnected
- Invalid redirect_uri
- Error processing end session request
- Unexpected end of request content
-- this one actually is also interesting as logged twice - once by IdentityServerMiddleware and then by Kestrel..

I understand it can be many requirements for these errors and different ways of handling them. We are reacting also to error count which in this case is misleading and thus we need to implement some logger filters to either change level or not to log them to certain sinks.

Would it be possible to improve these logs? Maybe even implementing dedicated logging class with dedicated methods for each situation which can be overridden by user code?
